config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'

  devise_for :users

  resources :municipes, except: %i[destroy] do
    patch :toggle, on: :member
  end
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  belongs_to :municipe

  validates :zip_code, presence: true, zip_code: { allow_blank: true }
  validates :street, presence: true
  validates :number, presence: true, format: { with: /\A(\d+[a-z]?|)\z/i, allow_blank: true }
  validates :neighbourhood, presence: true
  validates :city, presence: true
  validates :state, presence: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/municipe.rb
# frozen_string_literal: true

class Municipe < ApplicationRecord
  enum :status, { active: 'active', inactive: 'inactive' }, validate: true

  has_one :address, dependent: :destroy
  has_one_attached :photo do |attachable|
    attachable.variant :thumb, resize: '100x100'
    attachable.variant :medium, resize: '300x300'
  end

  accepts_nested_attributes_for :address, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true
  validates :cpf, presence: true,
                  cpf: { allow_blank: true },
                  uniqueness: { allow_blank: true }
  validates :cns, presence: true,
                  cns: { allow_blank: true },
                  uniqueness: { allow_blank: true }
  validates :email, presence: true,
                    email: { allow_blank: true }
  validates :birthday, date: { required: true, less_than: -> { Date.current } }
  validates :phone, presence: true, phone: { allow_blank: true }

  def toggle_status
    update status: active? ? :inactive : :active
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  private

  def adorne(record)
    @adornes ||= {}
    @adornes[record] ||= begin
      "#{record.class}Decorator".constantize.new record
    rescue StandardError
      ApplicationDecorator.new record
    end
  end
  helper_method :adorne
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/municipes_controller.rb
# frozen_string_literal: true

class MunicipesController < ApplicationController
  before_action :build_municipe_form, only: %i[new create]
  before_action :find_municipe_form, only: %i[edit update]

  # GET /municipes or /municipes.json
  def index; end

  # GET /municipes/1 or /municipes/1.json
  def show; end

  # GET /municipes/new
  def new; end

  # GET /municipes/1/edit
  def edit; end

  # POST /municipes or /municipes.json
  def create
    municipe.attributes = municipe_params

    respond_to do |format|
      if municipe.save
        format.html { redirect_to edit_municipe_url(municipe), notice: 'Municipe was successfully created.' }
        format.json { render :show, status: :created, location: municipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: municipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /municipes/1 or /municipes/1.json
  def update
    respond_to do |format|
      if municipe.update(municipe_params)
        format.html { redirect_to edit_municipe_url(municipe), notice: 'Municipe was successfully updated.' }
        format.json { render :show, status: :ok, location: municipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: municipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH /municipes/1/toggle or /municipes/1/toggle.json
  def toggle
    respond_to do |format|
      if municipe.toggle_status
        format.html { redirect_to edit_municipe_url(municipe), notice: 'Municipe was successfully updated.' }
        format.json { render :show, status: :ok, location: municipe }
      end
    end
  end

  # DELETE /municipes/1 or /municipes/1.json
  def destroy
    municipe.destroy!

    respond_to do |format|
      format.html { redirect_to municipes_url, notice: 'Municipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def resource_path(resource)
    return resource if resource.persisted?

    municipes_path
  end
  helper_method :resource_path

  def build_municipe_form
    @municipe = MunicipeForm.new
  end

  def find_municipe_form
    @municipe = MunicipeForm.new municipe_id: params[:id]
  end

  def municipe
    @municipe ||= Municipe.find(params[:id])
  end
  helper_method :municipe

  def municipes
    @municipes ||= Municipe.all
  end
  helper_method :municipes

  # Only allow a list of trusted parameters through.
  def municipe_params
    params.require(:municipe).permit(
      :name, :cpf, :cns, :email, :birthday, :phone, :photo, :street, :number,
      :complement, :neighbourhood, :city, :state, :ibge, :zip_code
    )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application/_alert.html.erb
<%- if notice.present? %>
  <p
    class="alert alert-success alert-dismissible fade show"
    role="alert"
  >
    <%= notice %>
    <%= button_tag '',
                  type: "button",
                  class: "btn-close",
                  data: { 'bs-dismiss': "alert" },
                  aria: { label: "Close" }
    %>
  </p>
<%- end %>

<%- if alert.present? %>
  <p
    class="alert alert-danger alert-dismissible fade show"
    role="alert"
  >
    <%= alert %>
    <%= button_tag '',
                  type: "button",
                  class: "btn-close",
                  data: { 'bs-dismiss': "alert" },
                  aria: { label: "Close" }
    %>
  </p>
<%- end %>

app/views/application/_menu.html.erb
<nav class="navbar navbar-expand-lg bg-danger-subtle rounded-top mb-2" data-bs-theme="light">
  <div class="container-fluid">
    <span class="navbar-brand">
      <%= image_tag 'logo-om30.png', title: 'OM30', height: 54 %>
    </span>
    <%= button_tag class: "navbar-toggler",
                   type: "button",
                   data: { 'bs-toggle': "collapse", 'bs-target': "#navbarSupportedContent" },
                   aria: { controls: "navbarSupportedContent", expanded: "false", label: "Toggle navigation"} do
    %>
      <span class="navbar-toggler-icon"></span>
    <%- end if user_signed_in? %>
    <%- if user_signed_in? %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to t(:'menus.home'),
                      root_url,
                      class: "nav-link #{:active if controller_name == 'home' }"
          %>
        </li>
        <li class="nav-item">
          <%= link_to t(:'menus.municipes'),
                      municipes_url,
                      class: "nav-link #{:active if controller_name == 'municipes' }"
          %>
        </li>
      </ul>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <%= link_to '#',
                      class: "nav-link dropdown-toggle #{:active if controller_name == 'registrations' }",
                      role: "button",
                      data: { 'bs-toggle': "dropdown" },
                      aria: { expanded: "false" } do
          %>
            <%= current_user.email %>
          <%- end %>
          <ul class="dropdown-menu">
            <li>
              <%= link_to t(:'menus.registrations.edit'),
                          edit_user_registration_url,
                          class: "dropdown-item"
              %>
            </li>
            <li><hr class="dropdown-divider"></li>
            <li>
              <%= link_to t(:'menus.sessions.delete'),
                          destroy_user_session_url,
                          data: { turbo_method: :delete },
                          class: 'dropdown-item'
              %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <%- end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teste OM30</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="text-bg-dark <%= controller_name %> <%= action_name %>">
    <div class="container-lg">

      <div class="card card-tall">
        <div class="card-body shadow">
          <%= render 'menu' %>
          <%= render 'alert' %>

          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/municipes/_form.html.erb
<%= simple_form_for(
  municipe,
  model_name: :municipe,
  url: resource_path(municipe.municipe),
  method: municipe.municipe.persisted? ? :put : :post,
  html: { multipart: true }) do |form|
%>
  <%#= form.error_notification %>
  <%= form.error_notification message: form.object.errors[:base].to_sentence if form.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= form.input :name %>
    <%= form.input :email %>
    <div class="row">
      <%= form.input :cpf,
                     input_html: { data: { mask: '999.999.999-99' } },
                     wrapper_html: { class: 'col-3' }
      %>
      <%= form.input :cns,
                     input_html: { data: { mask: '999 9999 9999 9999' } },
                     wrapper_html: { class: 'col-3' }
      %>
      <%= form.input :birthday,
                     as: :string,
                     input_html: {
                       readonly: true,
                       class: 'date',
                       value: adorne(municipe).birthday
                     },
                     wrapper_html: { class: 'col-3' }
      %>
      <%= form.input :phone,
                     input_html: { data: { mask: '+99 [99 ]9999[9]-9999' } },
                     wrapper_html: { class: 'col-3' }
      %>
    </div>

    <%= form.input :photo, as: :file %>

    <div class="row">
      <%= form.input :street,
                     wrapper_html: { class: 'col-4' }
      %>
      <%= form.input :number,
                     wrapper_html: { class: 'col-2' }
      %>
      <%= form.input :complement,
                     wrapper_html: { class: 'col-3' }
      %>
      <%= form.input :neighbourhood,
                     wrapper_html: { class: 'col-3' }
      %>
    </div>
    <div class="row">
      <%= form.input :city,
                     wrapper_html: { class: 'col-6' }
      %>
      <%= form.input :state,
                     wrapper_html: { class: 'col-2' }
      %>
      <%= form.input :ibge, wrapper_html: { class: 'col-2' } %>
      <%= form.input :zip_code,
                     input_html: { data: { mask: '99999-999' } },
                     wrapper_html: { class: 'col-2' }
      %>
    </div>
  </div>

  <div class="form-actions">
    <%= form.button :submit, class: 'btn btn-primary' %>
    <%= link_to t(:'buttons.municipes.index'), municipes_path, class: 'btn btn-link float-end' %>

    <%= link_to toggle_municipe_path(municipe.municipe),
                data: { turbo_method: :patch },
                class: 'btn btn-link float-end' do
    %>
      <%= municipe.municipe.inactive? ? t(:'buttons.municipes.active') : t(:'buttons.municipes.inactive') %>
    <%- end if municipe.municipe.persisted? %>
  </div>
<%- end %>

app/views/municipes/edit.html.erb
<h3><%= t :'titles.municipes.edit'%></h3>

<%= render "form" %>

app/views/municipes/index.html.erb
<h3>
  <%= t 'titles.municipes.index' %>

  <%= link_to t(:'buttons.municipes.new'),
              new_municipe_path,
              class: 'btn btn-outline-secondary float-end'
  %>
</h3>

<div id="municipes table-responsive">
  <table class="table table-hover table-striped align-middle">
    <thead>
      <tr>
        <th><%= Municipe.human_attribute_name :id %></th>
        <th><%= Municipe.human_attribute_name :name %></th>
        <th><%= Municipe.human_attribute_name :email %></th>
        <th><%= Municipe.human_attribute_name :phone %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <%- municipes.each do |municipe| %>
      <tr>
        <td><%= adorne(municipe).id %></td>
        <td><%= adorne(municipe).name %></td>
        <td><%= adorne(municipe).email %></td>
        <td><%= adorne(municipe).phone %></td>
        <td>
          <%= link_to edit_municipe_path(municipe),
                      class: 'btn btn-secondary',
                      title: t(:'buttons.municipes.edit') do
          %>
            <i class="bi bi-pencil-square"></i>
          <%- end %>
        </td>
      </tr>
      <p>
      </p>
    <%- end %>
    </tbody>
  </table>
</div>

app/views/municipes/new.html.erb
<h3><%= t :'titles.municipes.new'%></h3>

<%= render "form" %>